# Generated by Django 5.1.4 on 2025-01-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
