# Generated by Django 5.1.4 on 2025-01-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
